import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { log } from '../log.ts'
import type {
	QVACCompletionEvent,
	QVACCompletionOptions,
	QVACHeartbeatOptions,
	QVACLoadModelOptions,
	QVACProviderHandle,
	QVACSDK,
	QVACStartProviderOptions,
} from './types.ts'

const BRIDGE_SCRIPT = `// Auto-generated by OmniMesh SDK bridge
import * as sdk from '@qvac/sdk';
process.stdin.setEncoding('utf8');
let buf = '';
process.stdin.on('data', (chunk) => {
  buf += chunk;
  const lines = buf.split('\\n');
  buf = lines.pop() || '';
  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      handle(JSON.parse(line));
    } catch (e) {}
  }
});
process.stdin.on('end', () => process.exit(0));
async function handle(req) {
  try {
    const r = await dispatch(req.m, req.p);
    respond(req.id, r);
  } catch (e) {
    respond(req.id, null, e.message);
  }
}
function respond(id, result, error) {
  process.stdout.write(JSON.stringify({ id, r: result, e: error }) + '\\n');
}
async function dispatch(m, p) {
  switch (m) {
    case 'startProvider': {
      const h = await sdk.startQVACProvider(p);
      return { publicKey: h.publicKey };
    }
    case 'stopProvider': {
      if (sdk.stopQVACProvider) await sdk.stopQVACProvider();
      return null;
    }
    case 'loadModel': return await sdk.loadModel(p);
    case 'unloadModel': { await sdk.unloadModel(p.modelId); return null; }
    case 'completion': {
      const run = sdk.completion(p);
      const evs = [];
      for await (const ev of run.events) evs.push(ev);
      return { events: evs };
    }
    case 'heartbeat': {
      if (!sdk.heartbeat) throw new Error('heartbeat not available');
      return await sdk.heartbeat(p);
    }
    case 'ping': return 'pong';
    default: throw new Error('unknown method: ' + m);
  }
}
`

function bridgeScriptPath(): string {
	const home = process.env.HOME || process.env.USERPROFILE || ''
	const dir = path.join(home, '.omni')
	if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
	const fp = path.join(dir, 'sdk-bridge.mjs')
	if (!existsSync(fp)) writeFileSync(fp, BRIDGE_SCRIPT, 'utf8')
	return fp
}

let bridge: NodeBridgeSDK | null = null
let reqId = 0

interface BridgeResponse {
	id: number
	r: unknown
	e: string | null
}

function respLine(data: string): BridgeResponse | null {
	try {
		const o = JSON.parse(data) as BridgeResponse
		if (typeof o.id === 'number') return o
		return null
	} catch {
		return null
	}
}

class NodeBridgeSDK implements QVACSDK {
	private proc: ReturnType<typeof Bun.spawn> | null = null
	private pending = new Map<
		number,
		{ resolve: (v: unknown) => void; reject: (e: Error) => void }
	>()
	private buf = ''

	async start(): Promise<boolean> {
		if (this.proc) return true
		try {
			const script = bridgeScriptPath()
			this.proc = Bun.spawn({
				cmd: ['node', script],
				stdin: 'pipe',
				stdout: 'pipe',
				stderr: 'inherit',
				env: process.env,
			})
			const stdout = this.proc
				.stdout as unknown as ReadableStream<Uint8Array> | null
			if (!stdout) {
				throw new Error('bridge stdout unavailable')
			}
			const reader = (
				stdout as unknown as {
					getReader: () => ReadableStreamDefaultReader<Uint8Array>
				}
			).getReader()
			this.readLoop(reader)
			const pong = await this.request('ping', null)
			return pong === 'pong'
		} catch (err) {
			log.warn(`SDK bridge start failed: ${(err as Error).message}`)
			this.cleanup()
			return false
		}
	}

	private async readLoop(reader: {
		read: () => Promise<{ done: boolean; value?: Uint8Array }>
	}) {
		try {
			while (true) {
				const { done, value } = await reader.read()
				if (done) break
				if (!value) continue
				this.buf += new TextDecoder().decode(value)
				const lines = this.buf.split('\n')
				this.buf = lines.pop() || ''
				for (const line of lines) {
					if (!line.trim()) continue
					const resp = respLine(line)
					if (!resp) continue
					const p = this.pending.get(resp.id)
					if (!p) continue
					this.pending.delete(resp.id)
					if (resp.e) p.reject(new Error(resp.e))
					else p.resolve(resp.r)
				}
			}
		} catch {
			// stream ended
		}
		this.cleanup()
	}

	private request(method: string, params: unknown): Promise<unknown> {
		return new Promise((resolve, reject) => {
			const id = ++reqId
			this.pending.set(id, { resolve, reject })
			const msg = `${JSON.stringify({ id, m: method, p: params })}\n`
			const stdin = this.proc?.stdin
			if (stdin && typeof stdin !== 'number') {
				// FileSink in Bun has its own .write() method
				;(stdin as { write: (d: Uint8Array) => unknown }).write(
					new TextEncoder().encode(msg),
				)
			} else {
				this.pending.delete(id)
				reject(new Error('bridge not running'))
			}
			setTimeout(() => {
				const p = this.pending.get(id)
				if (!p) return
				this.pending.delete(id)
				reject(new Error(`bridge timeout: ${method}`))
			}, 30_000)
		})
	}

	private cleanup() {
		if (this.proc) {
			try {
				const stdin = this.proc.stdin
				if (stdin && typeof stdin !== 'number') {
					;(stdin as { end?: () => void }).end?.()
				}
				this.proc.kill()
			} catch {
				/* ignore */
			}
			this.proc = null
		}
		for (const [, p] of this.pending) p.reject(new Error('bridge disconnected'))
		this.pending.clear()
	}

	async stop() {
		this.cleanup()
	}

	// QVACSDK implementation
	async startQVACProvider(
		options: QVACStartProviderOptions,
	): Promise<QVACProviderHandle> {
		const r = (await this.request('startProvider', options)) as {
			publicKey: string
		}
		// stopQVACProvider must be called; we ignore the handle's stop() since the bridge handles it
		return {
			publicKey: r.publicKey,
			stop: async () => {
				await this.stopQVACProvider()
			},
		}
	}

	async stopQVACProvider(): Promise<void> {
		await this.request('stopProvider', null)
	}

	async loadModel(options: QVACLoadModelOptions): Promise<string> {
		return (await this.request('loadModel', options)) as string
	}

	async unloadModel(modelId: string): Promise<void> {
		await this.request('unloadModel', { modelId })
	}

	completion(options: QVACCompletionOptions): {
		events: AsyncIterable<QVACCompletionEvent>
	} {
		const promise = this.request('completion', options) as Promise<{
			events: QVACCompletionEvent[]
		}>
		async function* gen() {
			const r = await promise
			for (const ev of r.events) yield ev
		}
		return { events: gen() }
	}

	async heartbeat(
		options: QVACHeartbeatOptions,
	): Promise<{ rttMs: number; reachable: boolean }> {
		return (await this.request('heartbeat', options)) as {
			rttMs: number
			reachable: boolean
		}
	}

	// Not yet implemented via bridge
	getLoadedModelInfo = undefined
	modelRegistryList = undefined
	modelRegistrySearch = undefined
	modelRegistryGetModel = undefined
	downloadAsset = undefined
	cancel = undefined
	suspend = undefined
	resume = undefined
}

export async function tryNodeBridge(): Promise<QVACSDK | null> {
	if (bridge) return bridge
	try {
		const b = new NodeBridgeSDK()
		const ok = await b.start()
		if (!ok) {
			b.stop()
			return null
		}
		bridge = b
		return b
	} catch {
		return null
	}
}
